# All, included Dusk, works

# Use an official Ubuntu base image
FROM ubuntu:20.04

RUN apt-get update

RUN apt-get install ca-certificates apt-transport-https software-properties-common lsb-release -y
RUN apt-get install -y curl unzip

RUN add-apt-repository ppa:ondrej/php -y

RUN apt-get update

# Install PHP 8.2
RUN apt-get install -y php8.2

# Install PHP 8.2 Extensions
RUN apt-get install -y php8.2-cli \
    php8.2-fpm

RUN apt-get install -y php8.2-mysql
RUN apt-get install -y php8.2-mbstring
RUN apt-get install -y php8.2-xml
RUN apt-get install -y php8.2-curl
RUN apt-get install -y php8.2-zip
RUN apt-get install -y php8.2-bcmath

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install browser for Laravel Dusk
#RUN apt-get install -y chromium-browser \
#    chromium-chromedriver

# Install Google Chrome
RUN mkdir browser
WORKDIR /browser
RUN curl -O https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt install -y ./google-chrome-stable_current_amd64.deb

# Prepare work folder
RUN cd /home && mkdir html
WORKDIR /home/html

# Get project
RUN composer create-project laravel/laravel .

# Install Dusk
RUN composer require --dev laravel/dusk
RUN php artisan dusk:install

# Update files
# --no-sandbox added in DusktestCase.php
# .env APP_URL=http://127.0.0.1:8000 

# Test it
# php artisan serve - at first you have to run (in aother window docker exec -it NAME bash)
# php artisan dusk - then will work, for check if all runs


# IDK if needed php artisan dusk:chrome-driver 120 # 120.0.6099.109
# IDK if needed chmod -R 0755 vendor/laravel/dusk/bin/
